### ISSUE TITLE
Return probabilities (not just best match)

### ISSUE THREAD

**Issue by jochemstoel** [nemo/natural-synaptic#12]
What do you suggest is the best way to get all probability values from the classifier rather than the best match only? For instance an Array or Object of all classifications sorted by probability.

```js
classifier.classify('there is something wrong with my computer system')
// software: 0.8, hardware: 0.9
```

**Comment by nemo** [comment]
Use the `getClassifications` function instead:

```javascript

classifier. getClassifications('there is something wrong with my computer system')
```
