### ISSUE TITLE
REPEATED TRAINING

### ISSUE THREAD

**Issue by ohenepee** [nemo/natural-synaptic#2]
I'm fairly a beginner in NN, what I would love to know is: will adding documents and training time after time have any negative effect on the results of the first batch of documents that were added?

E.g.
Day 1: add and train 20 docs... SAVE neural network to file
Day 2: load neural network and add a new/different set of documents and train... SAVE
.....
Day #n (~100): load neural network and classify some text... **will it give the correct class for items added on day 1 all the way through let's say day 12?**

**Comment by nemo** [comment]
@ohenepee this isn't technically setup for continuous learning as the training process starts everything from scratch (as opposed to just doing a backward pass when a new document is added).

The way we've structured it is to essentially just use the pre-trained models in production and do training in batches as new data becomes available once in a while.

**Comment by ohenepee** [comment]
Okay thanks
