### ISSUE TITLE
Does not work with Cyrillic text

### ISSUE THREAD

**Issue by injaan** [nemo/natural-synaptic#8]
It cannot classify Cyrillic texts, or is that only work with English language?
-----------------
TypeError: Cannot read property 'output' of undefined
    at FeedForwardNetwork.train (\project_path\node_modules\natural-synaptic\lib\FeedForwardNetwork.js:32:49)

**Comment by nemo** [comment]
@tobi418 Definitely not meant to be used with non-English languages at this point.
